services:
  - type: web
    name: campus-event-backend
    env: node
    plan: free
    buildCommand: npm install && npm run postinstall
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
